Added SQL to backend development languages
Timonwa/techroadmap pull request #119
Opened 2023-08-19 05:45 UTC by lokytech5

Added sql roadmap to backend languages. please compare and let me know. thanks

2023-09-09 21:59 UTC, lokytech5 commented
Review and let me know

2023-09-12 08:56 UTC, Timonwa commented
@lokytech5, the links for the playlist, add the direct link to the playlist and not a link to one of the videos in the playlist.

2023-09-12 08:58 UTC, Timonwa requested changes

2023-09-12 08:58 UTC, Timonwa commented on components/backendPageContent/BackendLangs.js
> +              <ResourceLink>
Let this link come first

2023-09-12 08:58 UTC, Timonwa commented on components/backendPageContent/BackendLangs.js
> +                <a target="_blank" href="https://towardsdatascience.com/10-quick-sql-tips-after-writing-daily-in-sql-for-3-years-37bdba0637d0">
This article has a paywall. Can you replace it with one that doesn't require payment before accessing it?

2023-10-12 08:48 UTC, closed without merging