Added more database languages
Timonwa/techroadmap pull request #123
Opened 2023-09-26 17:43 UTC by haseeb196

# Issue #56 
## Added more database languages

2023-10-02 17:49 UTC, Timonwa requested changes
I have reviewed your contribution and requested a few updates. 
Also, please add the database to the side menu and ensure that it links properly to the section. If you have any issues, I am here to help you.

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                    href="https://www.youtube.com/watch?v=-ARMty_N0RU&list=PL3bGLnkkGnuUOB9YjjVDty6aCJApvkw8O&pp=iAQB"
Can you replace this link with the link for the playlist? This link is one for the first article in the playlist.

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                  MariaDB Tutorial
Is there a reason why you linked the 'Getting Started' page instead of the 'Home' page?

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                    CRUD Application with Express and MariaDB
Can you replace the text with `Building a CRUD application with Express and MariaDB in typescript` so that readers can know that it includes Typescript too?

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                  Application with CouchDB and JS
You forgot to add the author's name. You can label this article instead of a link since it is an article.

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                   Firestore for Beginners ~ Net Ninja
The also should be linked to the playlist instead of the first video.

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                  <ResourceBadge>Link</ResourceBadge>
You can label this article, instead of link, since it is an article.

2023-10-02 17:49 UTC, Timonwa commented on components/backendPageContent/Database.js
> +                  Application Using Firestore and NextJS
You can label this article instead of a link since it is an article, too. And add the publication name.

2023-10-03 19:41 UTC, haseeb196 commented
> I have reviewed your contribution and requested a few updates. Also, please add the database to the side menu and ensure that it links properly to the section. If you have any issues, I am here to help you.

All changes are done. can u review it?

2023-10-09 10:00 UTC, Timonwa commented
@haseeb196 i will review them now

2023-10-10 06:04 UTC, Timonwa commented
Awesome job @haseeb196 👍🏽

2023-10-10 06:04 UTC, Timonwa approved these changes

2023-10-10 06:15 UTC, merged