Feat/material UI
Timonwa/techroadmap pull request #145
Opened 2023-10-07 18:15 UTC by Alexandra2888

-I've added Material UI at CSS resources (article & some videos)

2023-10-07 20:28 UTC, Timonwa requested changes
The resources look good. except for one that confuses me.
Also pls add Material UI to the side menu

2023-10-07 20:28 UTC, Timonwa commented on components/frontendPageContent/CssFrameworks.js
> +              <a
I cant find a video on this is, it looks more like an article. Can you clarify what this link is about?

2023-10-07 20:28 UTC, Timonwa commented on components/frontendPageContent/CssFrameworks.js
> +                Material UI 5 (MUI) React Tutorial | MUI Responsive Real Project
Let this link be the second on the list. It should be directly below the website link. and add the `video` badge to it.

2023-10-07 20:28 UTC, Timonwa commented on components/frontendPageContent/CssFrameworks.js
> +                Code a Dictionary with React and Material UI ~ FreeCodeCamp
Then, let this link be the third on the list.

2023-10-08 09:17 UTC, Alexandra2888 commented on components/frontendPageContent/CssFrameworks.js
> +              <a
Line 297-302: MUI documentation link
```           ResourceLink>
              <ResourceBadge></ResourceBadge>
              <a target="_blank" href="https://mui.com/">
                 Official Website
              </a>
              <ResourceBadge>Link</ResourceBadge>
            </ResourceLink>
            ```

2023-10-08 09:18 UTC, Alexandra2888 commented on components/frontendPageContent/CssFrameworks.js
> +                Material UI 5 (MUI) React Tutorial | MUI Responsive Real Project
Line 314-322:
```  <ResourceLink>
              <a
                target="_blank"
                href="https://www.youtube.com/watch?v=fzxEECHnsvU"
              >
                Material UI 5 (MUI) React Tutorial | MUI Responsive Real Project
                ~ Lama Dev
              </a>
              <ResourceBadge>Video</ResourceBadge>
            </ResourceLink>
            ```

2023-10-08 09:19 UTC, Alexandra2888 commented on components/frontendPageContent/CssFrameworks.js
> +                Code a Dictionary with React and Material UI ~ FreeCodeCamp
✓

2023-10-08 09:20 UTC, Alexandra2888 commented
Changes done! Hope it's OK now :)
ps: If I have time can I contribute more?

2023-10-09 09:58 UTC, Timonwa requested changes
Thank you, @Alexandra2888. Sure, you can contribute as often as you like.

But there is a bug now: an empty badge before the website link. Also, can you remove the CodingNinja link? Its content is confusing.

![FireShot Capture 032 - How to Become a Frontend Developer in 2023  - Frontend Developer Road_ - techroadmap-38gj8dfmy-timonwa vercel app](https://github.com/Timonwa/techroadmap/assets/63044364/efe8fb11-3c23-4498-a964-32e9424e4b7a)

2023-10-10 05:57 UTC, Timonwa commented
awesome. 👍🏽

2023-10-10 05:58 UTC, Timonwa approved these changes

2023-10-10 05:59 UTC, merged