added links frontend development page: javascript and design resources
Timonwa/techroadmap pull request #52
Opened 2022-05-13 14:34 UTC by senali-d

Reference Issues
Closes https://github.com/Timonwa/techroadmap/issues/15

What does this implement/fix?

1. Added Javascript tips and tricks, tools, cool examples etc -> [Codepen](https://codepen.io/) - The best place to build, test, and discover front-end code.
2. Added Design Resources tips and tricks, tools, cool examples etc -> [Fontello](https://fontello.com/) - icon fonts generator

2022-05-13 15:39 UTC, Timonwa requested changes

2022-05-13 15:39 UTC, Timonwa commented on src/components/frontendPageContent/JsBasics.js
> +              <ResourceBadge>Tool</ResourceBadge>
Codepen is already listed in the code editors section. So there's no need to repeat it again.
https://techroadmap-bit8o7sgw-timonwa.vercel.app/frontend#online-editors

2022-05-13 15:39 UTC, Timonwa commented on src/components/frontendPageContent/DesignResources.js
> +              <a target="_blank" href="https://fontello.com/">Fontello - icon fonts generator</a>
You can add this to the *Icons* list instead of placing it in the *Others* list .
https://techroadmap-bit8o7sgw-timonwa.vercel.app/frontend#icons

2022-05-13 15:41 UTC, Timonwa commented
Welcome @senali-d and thank you for your pull request.
I have requested a few corrections, please do them before I can merge your request.

2022-05-14 05:34 UTC, senali-d commented on src/components/frontendPageContent/JsBasics.js
> +              <ResourceBadge>Tool</ResourceBadge>
Just removeit

2022-05-14 05:35 UTC, senali-d commented on src/components/frontendPageContent/DesignResources.js
> +              <a target="_blank" href="https://fontello.com/">Fontello - icon fonts generator</a>
Added to icon list

2022-05-14 07:54 UTC, Timonwa approved these changes

2022-05-14 07:58 UTC, merged

2022-11-03 12:21 UTC, Timonwa commented
@all-contributors please add @senali-d for code and data